/**
 * Sentry instrumentation placeholder.
 * TODO: Run `npx @sentry/wizard@latest -i nextjs` to fully configure Sentry.
 * TODO: Add NEXT_PUBLIC_SENTRY_DSN to .env.local.
 */

export function initSentry(): void {
  // Initialization is handled by sentry.client.config.ts / sentry.server.config.ts
  // generated by the Sentry wizard. This file is a placeholder for custom setup.
  if (process.env.NEXT_PUBLIC_SENTRY_DSN) {
    // Sentry is configured via next.config.js withSentryConfig wrapper.
    // See: https://docs.sentry.io/platforms/javascript/guides/nextjs/
  }
}

export function captureException(error: unknown, context?: Record<string, unknown>): void {
  if (process.env.NEXT_PUBLIC_SENTRY_DSN && typeof window !== "undefined") {
    // TODO: Import and use Sentry.captureException once SDK is configured
    // Sentry.captureException(error, { extra: context });
    console.error("[Sentry placeholder] captureException:", error, context);
  }
}

export function captureMessage(message: string, level: "info" | "warning" | "error" = "info"): void {
  if (process.env.NEXT_PUBLIC_SENTRY_DSN) {
    // TODO: Import and use Sentry.captureMessage once SDK is configured
    // Sentry.captureMessage(message, level);
    console.log(`[Sentry placeholder] captureMessage [${level}]:`, message);
  }
}
